Have a non-directory at the top, so creating directory top_dir
Adding /home/olivia/sylar/myserver/serverTest/olivia/./address.cpp to top_dir
Adding /home/olivia/sylar/myserver/serverTest/olivia/./address.h to top_dir
Adding /home/olivia/sylar/myserver/serverTest/olivia/./bytearray.cpp to top_dir
Adding /home/olivia/sylar/myserver/serverTest/olivia/./bytearray.h to top_dir
Adding /home/olivia/sylar/myserver/serverTest/olivia/./config.cpp to top_dir
Adding /home/olivia/sylar/myserver/serverTest/olivia/./config.h to top_dir
Adding /home/olivia/sylar/myserver/serverTest/olivia/./endian.h to top_dir
Adding /home/olivia/sylar/myserver/serverTest/olivia/./fd_manager.cpp to top_dir
Adding /home/olivia/sylar/myserver/serverTest/olivia/./fd_manager.h to top_dir
Adding /home/olivia/sylar/myserver/serverTest/olivia/./fiber.cpp to top_dir
Adding /home/olivia/sylar/myserver/serverTest/olivia/./fiber.h to top_dir
Adding /home/olivia/sylar/myserver/serverTest/olivia/./hook.cpp to top_dir
Adding /home/olivia/sylar/myserver/serverTest/olivia/./hook.h to top_dir
Creating filelist for http
Adding /home/olivia/sylar/myserver/serverTest/olivia/./io_manager.cpp to top_dir
Adding /home/olivia/sylar/myserver/serverTest/olivia/./io_manager.h to top_dir
Adding /home/olivia/sylar/myserver/serverTest/olivia/./log.cpp to top_dir
Adding /home/olivia/sylar/myserver/serverTest/olivia/./log.h to top_dir
Adding /home/olivia/sylar/myserver/serverTest/olivia/./macro.h to top_dir
Adding /home/olivia/sylar/myserver/serverTest/olivia/./mutex.cpp to top_dir
Adding /home/olivia/sylar/myserver/serverTest/olivia/./mutex.h to top_dir
Adding /home/olivia/sylar/myserver/serverTest/olivia/./noncopyable.h to top_dir
Adding /home/olivia/sylar/myserver/serverTest/olivia/./scheduler.cpp to top_dir
Adding /home/olivia/sylar/myserver/serverTest/olivia/./scheduler.h to top_dir
Adding /home/olivia/sylar/myserver/serverTest/olivia/./singleton.h to top_dir
Adding /home/olivia/sylar/myserver/serverTest/olivia/./sloccount.sc to top_dir
Adding /home/olivia/sylar/myserver/serverTest/olivia/./socket.cpp to top_dir
Adding /home/olivia/sylar/myserver/serverTest/olivia/./socket.h to top_dir
Adding /home/olivia/sylar/myserver/serverTest/olivia/./stream.cpp to top_dir
Adding /home/olivia/sylar/myserver/serverTest/olivia/./stream.h to top_dir
Creating filelist for streams
Adding /home/olivia/sylar/myserver/serverTest/olivia/./tcp_server.cpp to top_dir
Adding /home/olivia/sylar/myserver/serverTest/olivia/./tcp_server.h to top_dir
Adding /home/olivia/sylar/myserver/serverTest/olivia/./thread.cpp to top_dir
Adding /home/olivia/sylar/myserver/serverTest/olivia/./thread.h to top_dir
Adding /home/olivia/sylar/myserver/serverTest/olivia/./timer.cpp to top_dir
Adding /home/olivia/sylar/myserver/serverTest/olivia/./timer.h to top_dir
Adding /home/olivia/sylar/myserver/serverTest/olivia/./uri.h to top_dir
Adding /home/olivia/sylar/myserver/serverTest/olivia/./uri.rl to top_dir
Adding /home/olivia/sylar/myserver/serverTest/olivia/./uri.rl.cpp to top_dir
Adding /home/olivia/sylar/myserver/serverTest/olivia/./util.cpp to top_dir
Adding /home/olivia/sylar/myserver/serverTest/olivia/./util.h to top_dir
Categorizing files.
Computing results.


6611	cpp	http	/home/olivia/sylar/myserver/serverTest/olivia/http/http11_parser.rl.cpp
214	cpp	http	/home/olivia/sylar/myserver/serverTest/olivia/http/http_parser.cpp
445	cpp	http	/home/olivia/sylar/myserver/serverTest/olivia/http/http_connection.cpp
112	cpp	http	/home/olivia/sylar/myserver/serverTest/olivia/http/servlet.cpp
246	cpp	http	/home/olivia/sylar/myserver/serverTest/olivia/http/http.cpp
69	cpp	http	/home/olivia/sylar/myserver/serverTest/olivia/http/http_session.cpp
3252	cpp	http	/home/olivia/sylar/myserver/serverTest/olivia/http/httpclient_parser.rl.cpp
42	cpp	http	/home/olivia/sylar/myserver/serverTest/olivia/http/http_server.cpp
31	cpp	http	/home/olivia/sylar/myserver/serverTest/olivia/http/httpclient_parser.h
136	cpp	http	/home/olivia/sylar/myserver/serverTest/olivia/http/http_connection.h
32	cpp	http	/home/olivia/sylar/myserver/serverTest/olivia/http/http11_parser.h
48	cpp	http	/home/olivia/sylar/myserver/serverTest/olivia/http/http_parser.h
78	cpp	http	/home/olivia/sylar/myserver/serverTest/olivia/http/servlet.h
6	cpp	http	/home/olivia/sylar/myserver/serverTest/olivia/http/http11_common.h
26	cpp	http	/home/olivia/sylar/myserver/serverTest/olivia/http/http_server.h
273	cpp	http	/home/olivia/sylar/myserver/serverTest/olivia/http/http.h
16	cpp	http	/home/olivia/sylar/myserver/serverTest/olivia/http/http_session.h
83	cpp	streams	/home/olivia/sylar/myserver/serverTest/olivia/streams/socket_stream.cpp
29	cpp	streams	/home/olivia/sylar/myserver/serverTest/olivia/streams/socket_stream.h
45	lisp	top_dir	/home/olivia/sylar/myserver/serverTest/olivia/./sloccount.sc
281	cpp	top_dir	/home/olivia/sylar/myserver/serverTest/olivia/./address.cpp
475	cpp	top_dir	/home/olivia/sylar/myserver/serverTest/olivia/./bytearray.cpp
58	cpp	top_dir	/home/olivia/sylar/myserver/serverTest/olivia/./config.cpp
94	cpp	top_dir	/home/olivia/sylar/myserver/serverTest/olivia/./fd_manager.cpp
195	cpp	top_dir	/home/olivia/sylar/myserver/serverTest/olivia/./fiber.cpp
416	cpp	top_dir	/home/olivia/sylar/myserver/serverTest/olivia/./hook.cpp
361	cpp	top_dir	/home/olivia/sylar/myserver/serverTest/olivia/./io_manager.cpp
676	cpp	top_dir	/home/olivia/sylar/myserver/serverTest/olivia/./log.cpp
21	cpp	top_dir	/home/olivia/sylar/myserver/serverTest/olivia/./mutex.cpp
212	cpp	top_dir	/home/olivia/sylar/myserver/serverTest/olivia/./scheduler.cpp
383	cpp	top_dir	/home/olivia/sylar/myserver/serverTest/olivia/./socket.cpp
51	cpp	top_dir	/home/olivia/sylar/myserver/serverTest/olivia/./stream.cpp
116	cpp	top_dir	/home/olivia/sylar/myserver/serverTest/olivia/./tcp_server.cpp
64	cpp	top_dir	/home/olivia/sylar/myserver/serverTest/olivia/./thread.cpp
178	cpp	top_dir	/home/olivia/sylar/myserver/serverTest/olivia/./timer.cpp
10867	cpp	top_dir	/home/olivia/sylar/myserver/serverTest/olivia/./uri.rl.cpp
54	cpp	top_dir	/home/olivia/sylar/myserver/serverTest/olivia/./util.cpp
88	cpp	top_dir	/home/olivia/sylar/myserver/serverTest/olivia/./address.h
81	cpp	top_dir	/home/olivia/sylar/myserver/serverTest/olivia/./bytearray.h
348	cpp	top_dir	/home/olivia/sylar/myserver/serverTest/olivia/./config.h
48	cpp	top_dir	/home/olivia/sylar/myserver/serverTest/olivia/./endian.h
46	cpp	top_dir	/home/olivia/sylar/myserver/serverTest/olivia/./fd_manager.h
50	cpp	top_dir	/home/olivia/sylar/myserver/serverTest/olivia/./fiber.h
59	cpp	top_dir	/home/olivia/sylar/myserver/serverTest/olivia/./hook.h
55	cpp	top_dir	/home/olivia/sylar/myserver/serverTest/olivia/./io_manager.h
199	cpp	top_dir	/home/olivia/sylar/myserver/serverTest/olivia/./log.h
28	cpp	top_dir	/home/olivia/sylar/myserver/serverTest/olivia/./macro.h
162	cpp	top_dir	/home/olivia/sylar/myserver/serverTest/olivia/./mutex.h
12	cpp	top_dir	/home/olivia/sylar/myserver/serverTest/olivia/./noncopyable.h
108	cpp	top_dir	/home/olivia/sylar/myserver/serverTest/olivia/./scheduler.h
22	cpp	top_dir	/home/olivia/sylar/myserver/serverTest/olivia/./singleton.h
89	cpp	top_dir	/home/olivia/sylar/myserver/serverTest/olivia/./socket.h
21	cpp	top_dir	/home/olivia/sylar/myserver/serverTest/olivia/./stream.h
124	cpp	top_dir	/home/olivia/sylar/myserver/serverTest/olivia/./tcp_server.h
29	cpp	top_dir	/home/olivia/sylar/myserver/serverTest/olivia/./thread.h
57	cpp	top_dir	/home/olivia/sylar/myserver/serverTest/olivia/./timer.h
42	cpp	top_dir	/home/olivia/sylar/myserver/serverTest/olivia/./uri.h
24	cpp	top_dir	/home/olivia/sylar/myserver/serverTest/olivia/./util.h
